### ISSUE TITLE
pip install fail 

### ISSUE THREAD

**Issue by jutshanahan** [jasonh-n-austin/nasa-apod#1]
Hello,

Any idea what went wrong?

```
C:\Users\bobsyouruncle>pip install apod-wallpaper
Collecting apod-wallpaper
  Using cached apod-wallpaper-1.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\jshana~1\appdata\local\temp\pip-build-uo2ns7\apod-wallpaper\setup.py", line 21, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "c:\python27\lib\site-packages\pip\req\req_file.py", line 79, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\jshana~1\appdata\local\temp\pip-build-uo2ns7\apod-wallpaper\

```

**Comment by jharmn** [comment]
Hrm I'm not sure off-hand. Have you tried updating `pip`?

```
sudo pip install --upgrade pip
```

**Comment by jutshanahan** [comment]
Yes, tried that.  Also did this,
`pip install --upgrade setuptools`

**Comment by jharmn** [comment]
I just realized you're running this on windows. It was originally coded to work on Ubuntu 14.04, and I've installed it on Mac as well. I don't have any Windows machines to try it on. Generally speaking, getting PIL to install right is the big pain in the ass.
If you can get Pillow (a PIL fork) installed right, the irest should work OK. https://pillow.readthedocs.io/en/latest/installation.html#windows-installation

**Comment by fweik** [comment]
This is an issue with newer pip versions, independent of the platform, see #2

**Comment by jharmn** [comment]
Looks like #2 fixed this, so I'll close the issue.
